Repository ncar-xdev/jupyter-forward, pull requests merged in 2022-02, with the labels that each got.

#133 Fix bourne shell compatibility issues
  jupyter_forward/core.py
Labels: enhancement

#136 Update CI/tests to allow running proper, realistic unit tests
  .github/scripts/ssh_setup.sh
  .github/workflows/ci.yaml
  .github/workflows/upstream-dev-ci.yaml
  jupyter_forward/core.py
  setup.cfg
  tests/test_core.py
Labels: enhancement, CI

#138 Support more shells
  .github/scripts/ssh_setup.sh
  .github/workflows/ci.yaml
  .github/workflows/upstream-dev-ci.yaml
  .gitignore
  .pre-commit-config.yaml
  ci/environment-upstream-dev.yml
  ci/environment.yml
  jupyter_forward/cli.py
  jupyter_forward/console.py
  jupyter_forward/core.py
  jupyter_forward/helpers.py
  setup.cfg
  tests/misc.py
  tests/test_cli.py
  tests/test_core.py
  tests/test_helpers.py
Labels: enhancement, bugfix

#142 Update changelog
  CHANGELOG.md
Labels: documentation
